### ISSUE TITLE
Hello, the tensor file cannot be found while the program is running

### ISSUE THREAD

**Issue by baidu2018** [jsyoon0823/MRNN#1]
KeyError: "The name 'map/TensorArrayStack/TensorArrayGatherV3:0' refers to a Tensor which does not exist. The operation, 'map/TensorArrayStack/TensorArrayGatherV3', does not exist in the graph."
Is this caused by my configuration environment error?

**Comment by jsyoon0823** [comment]
I am not sure where the error comes from.
Maybe the tensorflow version issue. I used tensorflow 1.15 and I have not met this error.

**Comment by baidu2018** [comment]
Thank you very much! I will reinstall tensorflow and have a try.
